/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.astroapp;

import java.awt.BasicStroke;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.util.ArrayList;
import javax.swing.JPanel;

/**
 *
 * @author naksh
 */
public class ChartPosition extends javax.swing.JPanel {
   
    private ArrayList<Planets> al = new ArrayList<>();

    /**
     * Creates new form ChartPosition
     */
    public ChartPosition() {
        initComponents();
        Planets.addPlanetsChartDetails(al);

        JPanel p = new MyPanel();
        p.setPreferredSize(new Dimension(500, 500));
        p.setBackground(new Color(15, 23, 42));
        add(p);
//        repaint();
    }
    
    
    class MyPanel extends JPanel
    {
        @Override
        protected void paintComponent(Graphics g)
        {
            super.paintComponent(g);
            
            Graphics2D g2 = (Graphics2D) g;
            int height = getHeight();
            int width = getWidth();
            g2.setColor(new Color(255,215,0));
            g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
            g2.setStroke(new BasicStroke(3));
            Chart.makeChart(g2, height, width);
            addPlanetInChart(g2, height, width);
        }

        public void addPlanetInChart(Graphics2D g, int height, int width)
        {
            int ymid = (height / 2);
            int xmid = (width / 2);
            
            g.setFont(new Font("SansSerif", Font.BOLD, 14));
            g.setColor(Color.white);

            g.drawString(al.get(0).getName(), xmid-15, ymid-180);
            g.drawString(al.get(1).getName(), 100, 75);
            g.drawString(al.get(2).getName(), 50, 130);
            g.drawString(al.get(11).getName(), 360, 75);
            g.drawString(al.get(10).getName(), 420, 130);

            g.drawString(al.get(4).getName(), 50, 380);
            g.drawString(al.get(5).getName(), 100, 440);
            g.drawString(al.get(7).getName(), 362, 430);
            g.drawString(al.get(8).getName(), 420, 380);

            g.drawString(al.get(3).getName(), xmid-180, ymid);
            g.drawString(al.get(9).getName(), xmid+150, ymid);
            g.drawString(al.get(6).getName(), xmid-15, ymid+180);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(255, 255, 153));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}

