/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.astroapp;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author naksh
 */
public class NakshatraAndTheirLords extends javax.swing.JPanel {
    String[] columns = {"Nakshatra", "Lord of Nakshatra"};

    Object[][] mat = {
        {"Ashwini", "Ketu"},
        {"Bharni", "Shukra"},
        {"Kratika", "Surya"},
        {"Rohini", "Chandra"},
        {"Mrigshira", "Mangal"},
        {"Aardra", "Rahu"},
        {"Punrvasu", "Guru"},
        {"Pushya", "Shani"},
        {"Ashlesha", "Budh"},
        {"Magha", "Ketu"},
        {"Poorvaphalguni", "Shukra"},
        {"Uttaraphalguni", "Surya"},
        {"Hasta", "Chandra"},
        {"Chitra", "Mangal"},
        {"Swati", "Rahu"},
        {"Vishakha", "Guru"},
        {"Anuradha", "Shani"},
        {"Jyeshtha", "Budh"},
        {"Mool", "Ketu"},
        {"Poorvashadha", "Shukra"},
        {"Uttarashadha", "Surya"},
        {"Shravan", "Chandra"},
        {"Dhanishtha", "Mangal"},
        {"Shatbhisha", "Rahu"},
        {"Poorvabhadrapada", "Guru"},
        {"Uttarabhadrapada", "Shani"},
        {"Revati", "Budh"}
    };
    /**
     * Creates new form NakshatraAndTheirLords
     */
    public NakshatraAndTheirLords() {
        initComponents();
        jt.setModel(new DefaultTableModel(mat, columns));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jt = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        jt.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jt);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Nakshatra and Lords");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 488, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 433, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jt;
    // End of variables declaration//GEN-END:variables
}
