/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.astroapp;

import java.awt.Color;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;

/**
 *
 * @author naksh
 */
public class PlanetaryFriendship extends javax.swing.JPanel {

    /**
     * Creates new form PlanetaryFriendship
     */
    
    private String colName[] = {"Planet Name", "Friend", "Neutral", "Enemies"};

    private Object mat[][] = {
    {"Sun", "Moon, Mars, Jupiter", "Mercury", "Venus, Saturn"},
    {"Moon", "Sun, Mercury", "Mars, Jupiter, Venus, Saturn", "None"},
    {"Mars", "Sun, Moon, Jupiter", "Venus, Saturn", "Mercury"},
    {"Mercury", "Sun, Venus", "Mars, Jupiter, Saturn", "Moon"},
    {"Jupiter", "Sun, Moon, Mars", "Saturn", "Mercury, Venus"},
    {"Venus", "Mercury, Saturn", "Mars, Jupiter", "Sun, Moon"},
    {"Saturn", "Mercury, Venus", "Jupiter", "Sun, Moon, Mars"},
    {"Rahu", "Venus, Saturn", "Mercury, Jupiter", "Sun, Moon, Mars"}, 
    {"Ketu", "Mars, Venus", "Mercury, Jupiter, Saturn", "Sun, Moon"}  
    };
    
    
    public PlanetaryFriendship() {
        initComponents();
        DefaultTableModel model = new DefaultTableModel();
        jt.setModel(model);
        
        
        model.setDataVector(mat, colName);
        
        JTableHeader header = jt.getTableHeader();
        header.setBackground(new Color(15, 23, 42));
        header.setForeground(Color.white);
        
        jt.getColumnModel().getColumn(0).setPreferredWidth(100);
        jt.getColumnModel().getColumn(1).setPreferredWidth(140);
        jt.getColumnModel().getColumn(2).setPreferredWidth(200);
        jt.getColumnModel().getColumn(3).setPreferredWidth(120);
        
        jt.setRowHeight(48);

        jt.setFillsViewportHeight(true);
        jt.setAutoCreateRowSorter(true);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jt = new javax.swing.JTable();

        setLayout(new java.awt.BorderLayout(10, 10));

        jScrollPane1.setBackground(new java.awt.Color(51, 0, 153));
        jScrollPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(25, 39, 71), 18));
        jScrollPane1.setForeground(new java.awt.Color(255, 255, 255));

        jt.setBackground(new java.awt.Color(0, 51, 153));
        jt.setFont(new java.awt.Font("Sans Serif Collection", 0, 12)); // NOI18N
        jt.setForeground(new java.awt.Color(255, 255, 255));
        jt.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jt);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jt;
    // End of variables declaration//GEN-END:variables
}
